name: CI Pipeline

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint with flake8
        run: |
          # Only warn, don't fail the build for style issues
          flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Run tests
        run: |
          # Only run pytest if test files exist
          if [ -f test_*.py ]; then pytest; else echo "No tests found"; fi